name: Deploy Jekyll Blog to Main Branch

on:
  push:
    branches:
      - blogging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the blogging branch
    - name: Check out blogging branch
      uses: actions/checkout@v3
      with:
        ref: blogging

    # Step 2: Set up Ruby environment
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    # Step 3: Install dependencies and build the site
    - name: Install dependencies and build
      run: |
        bundle install
        bundle exec jekyll build

    # Step 4: Check out the main branch
    - name: Check out main branch
      run: |
        git fetch origin main
        git checkout main

    # Step 5: Copy _site folder to blogs directory
    - name: Copy generated jekyll _site to the blogs folder
      run: |
        mkdir -p blogs
        rsync -av --delete _site/ blogs/
      env:
        ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # Step 6: Commit and push changes to main
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add blogs/
        git commit -m "Update blog contents from blogging branch and merge with for deployment" || true
        git push
